add

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,7 +6,7 @@ on:
   pull_request:
 
 jobs:
-  eslint:
+  setup:
     runs-on: ubuntu-latest
     steps:
       - name: ⬇️ Checkout repo
@@ -19,5 +19,24 @@ jobs:
           node-version-file: ".node-version"
       - name: 📥 Install deps
         run: npm install
-      - name: 🔬 Lint
+  lint:
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - name: ⚡️ESLint
         run: npm run lint
+  test:
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - name: 🧪Test
+        run: npm run coverage
+      - name: Check coverage
+        run: |
+          COVERAGE_THRESHOLD=90
+          TOTAL_COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
+          echo "total_coverage=$TOTAL_COVERAGE" >> $GITHUB_OUTPUT
+          if (( $(echo "$TOTAL_COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
+            echo "Code coverage is below ${COVERAGE_THRESHOLD}%. Failing the check."
+            exit 1
+          fi
